### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by pishguy** [TheDOme6/device_id#12]
```dart

E/MethodChannel#device_id(18872): Failed to handle method call
E/MethodChannel#device_id(18872): java.lang.SecurityException: getDeviceId: Neither user 10870 nor current process has android.permission.READ_PHONE_STATE.
E/MethodChannel#device_id(18872): 	at android.os.Parcel.readException(Parcel.java:1954)
E/MethodChannel#device_id(18872): 	at android.os.Parcel.readException(Parcel.java:1900)
E/MethodChannel#device_id(18872): 	at com.android.internal.telephony.IHwTelephony$Stub$Proxy.getUniqueDeviceId(IHwTelephony.java:1912)
E/MethodChannel#device_id(18872): 	at android.telephony.HwTelephonyManagerInner.getUniqueDeviceId(HwTelephonyManagerInner.java:1095)
E/MethodChannel#device_id(18872): 	at android.telephony.HwInnerTelephonyManagerImpl.getUniqueDeviceId(HwInnerTelephonyManagerImpl.java:340)
E/MethodChannel#device_id(18872): 	at android.telephony.TelephonyManager.getImei(TelephonyManager.java:1048)
E/MethodChannel#device_id(18872): 	at com.notrait.deviceid.DeviceIdPlugin.onMethodCall(DeviceIdPlugin.java:47)
E/MethodChannel#device_id(18872): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#device_id(18872): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#device_id(18872): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#device_id(18872): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#device_id(18872): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#device_id(18872): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#device_id(18872): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/MethodChannel#device_id(18872): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#device_id(18872): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#device_id(18872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter (18872): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, getDeviceId: Neither user 10870 nor current process has android.permission.READ_PHONE_STATE., null)
E/flutter (18872): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (18872): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (18872): <asynchronous suspension>
E/flutter (18872): #2      DeviceId.getIMEI (package:device_id/device_id.dart:22:40)
E/flutter (18872): <asynchronous suspension>
E/flutter (18872): #3      ScreenResisterUserState.register (package:kelide_jazzb/screens/pages/home/fragments/register/view/resigter_user.dart:258:38)
E/flutter (18872): <asynchronous suspension>
E/flutter (18872): #4      ScreenResisterUserState.build.<anonymous closure>.<anonymous closure> (package:kelide_jazzb/screens/pages/home/fragments/register/view/resigter_user.dart:164:52)
E/flutter (18872): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (18872): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (18872): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (18872): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (18872): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (18872): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (18872): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (18872): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (18872): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (18872): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (18872): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (18872): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (18872): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (18872): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (18872): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (18872): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (18872): #21     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (18872): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (18872): 
I/zygote64(18872): Do partial code cache collection, code=55KB, data=47KB
I/zygote64(18872): After code cache collection, code=55KB, data=47KB
I/zygote64(18872): Increasing code cache capacity to 256KB
```

**Comment by SarcasticNoodle** [comment]
Add the android.permission.READ_PHONE_STATE to your AndroidManifest.xml
