### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getID on channel device_id)

### ISSUE THREAD

**Issue by MichaelHipp** [TheDOme6/device_id#18]
I have this method:
```
Future<void> getID() async {
    _deviceID = await DeviceId.getID;
}
```

It throws this exception:
```
E/flutter ( 7032): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getID on channel device_id)
E/flutter ( 7032): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 7032): <asynchronous suspension>
E/flutter ( 7032): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7032): #2      DeviceId.getID (package:device_id/device_id.dart:13:39)
...
```
I'm using `device_id: ^0.2.0`. Any help?

**Comment by MichaelHipp** [comment]
Well evidently this is a common problem with Flutter and likely has nothing to do with this plugin. I solved it by stopping the debugger, doing 'flutter clean' in the terminal and restarting the app.

Found some discussion of it in this thread: flutter/flutter#10912 (comment) . That's where the idea of doing flutter clean came from.
